CREATE TABLE IF NOT EXISTS legs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exercise INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    date TEXT NOT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS push (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exercise INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    date TEXT NOT NULL,
    notes TEXT
);

CREATE TABLE IF NOT EXISTS pull (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    exercise INTEGER NOT NULL,
    sets INTEGER NOT NULL,
    reps INTEGER NOT NULL,
    weight INTEGER NOT NULL,
    date TEXT NOT NULL,
    notes TEXT
);

